name: patrol
description: >
  Powerful Flutter-native UI testing framework overcoming limitations of
  existing Flutter testing tools. Ready for action!
version: 2.2.2
homepage: https://patrol.leancode.co
repository: https://github.com/leancodepl/patrol
issue_tracker: https://github.com/leancodepl/patrol/issues

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  fixnum: ^1.0.1
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter 
  http: ^1.0.0
  integration_test:
    sdk: flutter
  json_annotation: ^4.8.1
  meta: ^1.7.0
  path: ^1.8.2
  patrol_finders: ^1.0.0
  shelf: ^1.4.1
  test_api: '>=0.4.0 <0.7.0'

dev_dependencies:
  build_runner: ^2.3.3
  json_serializable: ^6.7.1
  leancode_lint: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: pl.leancode.patrol
        pluginClass: PatrolPlugin
      ios:
        pluginClass: PatrolPlugin
      macos:
        pluginClass: PatrolPlugin
